apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-additional-scrape-configs
  namespace: monitoring
data:
  prometheus-additional.yaml: |
    scrape_configs:
      - job_name: 'django-app'
        metrics_path: /metrics
        scheme: http
        static_configs:
          - targets:
              - 'django-service.monitoring.svc.cluster.local:8000'

