prometheus:
  alertmanager:
    enabled: false

  pushgateway:
    enabled: false

  server:
    service:
      type: ClusterIP
      servicePort: 9090
      targetPort: 9090

  serverFiles:
    prometheus.yml:
      scrape_configs:
        - job_name: 'prometheus'
          static_configs:
            - targets:
                - 'localhost:9090'

        - job_name: 'django-app'
          metrics_path: /metrics
          scheme: http
          static_configs:
            - targets:
                - 'django-service.monitoring.svc.cluster.local:8000'

        - job_name: 'node-exporter'
          static_configs:
            - targets:
                - 'prometheus-prometheus-node-exporter.monitoring.svc.cluster.local:9100'

