apiVersion: v2
name: grafana
description: Grafana dashboard for Exchange monitoring
version: 0.1.0
dependencies:
  - name: grafana
    version: 8.5.0
    repository: https://grafana.github.io/helm-charts

