grafana:
  adminUser: admin
  adminPassword: admin

  service:
    type: NodePort
    nodePort: 30000

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          access: proxy
          url: http://prometheus-server.monitoring.svc.cluster.local:9090
          isDefault: true
          editable: false
        - name: Loki
          type: loki
          access: proxy
          url: http://loki.logging.svc.cluster.local:3100
          editable: false

